run: capture and display stdout/stderr on process failure
Before stdout/stderr wouldn't be correctly captured and the cause of process
failure could be hidden. Example exception messag before and after the fix,
showing an error where the IDD file path was passed incorrectly. Before:

EnergyPlusRunError:
Contents of EnergyPlus error file at /content/eplusout.err
<File not found>

After fix:

EnergyPlusRunError:
ERROR: Could not find input data dictionary: /tmp/tmpnooq09t4/EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/Energy+.idd.
Type 'energyplus --help' for usage.

Contents of EnergyPlus error file at /content/eplusout.err
<File not found>